# Generated by Django 5.0.4 on 2024-04-17 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activity', verbose_name='actividad'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1, verbose_name='día'),
        ),
        migrations.AlterField(
            model_name='event',
            name='goal',
            field=models.CharField(max_length=200, verbose_name='objetivo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(default=1, editable=False, verbose_name='prioridad'),
        ),
    ]
