# Generated by Django 5.0.4 on 2024-05-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='completado'),
        ),
    ]
