# Generated by Django 5.0.4 on 2024-05-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(choices=[('Mon', 'Lunes'), ('Tue', 'Martes'), ('Wed', 'Miércoles'), ('Thu', 'Jueves'), ('Fri', 'Viernes'), ('Sat', 'Sábado'), ('Sun', 'Domingo')], max_length=3, verbose_name='día'),
        ),
    ]
