# Generated by Django 5.0.4 on 2024-05-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_event_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='goal',
            field=models.CharField(blank=True, max_length=200, verbose_name='objetivo'),
        ),
    ]
