# Generated by Django 5.0.4 on 2024-05-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_event_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=40, verbose_name='nombre'),
        ),
    ]
