# Generated by Django 5.0.4 on 2024-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='prioridad'),
        ),
    ]
