# Generated by Django 5.0.4 on 2024-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_event_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
