# Generated by Django 5.0.4 on 2024-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_event_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=60, verbose_name='nombre'),
        ),
    ]
